const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

function upsertEnvValue(filePath, key, value) {
  let content = "";
  if (fs.existsSync(filePath)) {
    content = fs.readFileSync(filePath, "utf8");
  } else {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
  }

  const line = `${key}=${value}`;
  const pattern = new RegExp(`^${key}=.*$`, "m");
  if (pattern.test(content)) {
    content = content.replace(pattern, line);
  } else if (content.trim()) {
    content = `${content.trimEnd()}\n${line}\n`;
  } else {
    content = `${line}\n`;
  }
  fs.writeFileSync(filePath, content);
}

function syncArtifacts(contractName, address) {
  const artifactPath = path.resolve(__dirname, `../artifacts/contracts/${contractName}.sol/${contractName}.json`);
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  const backendDir = path.resolve(__dirname, "../../backend/app/contracts");
  fs.mkdirSync(backendDir, { recursive: true });
  fs.copyFileSync(artifactPath, path.join(backendDir, `${contractName}.json`));

  const frontendAbiPath = path.resolve(__dirname, "../../frontend/src/services/contractAbi.js");
  const frontendAbiModule = `// Auto-generated by contracts/scripts/deploy.js. Do not edit manually.\nexport const GIG_ESCROW_ABI = ${JSON.stringify(artifact.abi, null, 2)};\n\nexport default GIG_ESCROW_ABI;\n`;
  fs.writeFileSync(frontendAbiPath, frontendAbiModule);

  const addressInfoPath = path.resolve(__dirname, "contract-address.txt");
  const info = [
    `Contract: ${address}`,
    `Artifact: ${artifactPath}`,
    "",
    "Hardhat local network:",
    "RPC URL: http://127.0.0.1:8545",
    "Chain ID: 31337",
    "",
    "Import Account #0 private key into MetaMask for local testing:",
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
  ].join("\n");
  fs.writeFileSync(addressInfoPath, info);
}

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  console.log("\n=== Deploying GigEscrow ===\n");
  console.log("Deployer:", deployer.address);

  const GigEscrow = await hre.ethers.getContractFactory("GigEscrow");
  const escrow = await GigEscrow.deploy();
  await escrow.waitForDeployment();

  const address = await escrow.getAddress();
  console.log("GigEscrow deployed to:", address);

  const backendEnvPath = path.resolve(__dirname, "../../backend/.env");
  const frontendEnvPath = path.resolve(__dirname, "../../frontend/.env");

  try {
    upsertEnvValue(backendEnvPath, "CONTRACT_ADDRESS", address);
    upsertEnvValue(frontendEnvPath, "REACT_APP_CONTRACT_ADDRESS", address);
    console.log("Contract address synced to backend/.env and frontend/.env");
  } catch (err) {
    console.warn("WARNING: could not sync .env files:", err.message);
  }

  try {
    syncArtifacts("GigEscrow", address);
    console.log("ABI synced to backend and frontend");
  } catch (err) {
    console.warn("WARNING: could not sync artifacts:", err.message);
  }

  try {
    fs.writeFileSync(path.resolve(__dirname, "../.contract-address"), address);
    fs.writeFileSync("/app/.contract-address", address);
    console.log("Contract address written to .contract-address");
  } catch (err) {
    console.warn("WARNING: could not write .contract-address:", err.message);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
