class ErrorCodes:
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"

    BLOCKCHAIN_UNAVAILABLE = "BLOCKCHAIN_UNAVAILABLE"
    BLOCKCHAIN_NOT_CONFIGURED = "BLOCKCHAIN_NOT_CONFIGURED"
    BLOCKCHAIN_ABI_NOT_FOUND = "BLOCKCHAIN_ABI_NOT_FOUND"
    BLOCKCHAIN_TIMEOUT = "BLOCKCHAIN_TIMEOUT"
    BLOCKCHAIN_ERROR = "BLOCKCHAIN_ERROR"

    IPFS_UPLOAD_FAILED = "IPFS_UPLOAD_FAILED"
    IPFS_DOWNLOAD_FAILED = "IPFS_DOWNLOAD_FAILED"

    INTERNAL_ERROR = "INTERNAL_ERROR"
